### ISSUE TITLE
Implementation of Federated Loss

### ISSUE THREAD

**Issue by tonysy** [achalddave/large-vocab-devil#1]
Hi,
thanks for your sharing.
Could you share the implementation and experiment configuration of federated loss on LVIS?
Thanks a lot.

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest. We have released our original Federated loss implementation in the [CenterNet2](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/configs/LVIS_CenterNet2_R50_Fed_1x.yaml) repo. However, the parameters and results may not be identical to this project.

**Comment by tonysy** [comment]
@xingyizhou  Thanks a lot
