### ISSUE TITLE
AP values in paper

### ISSUE THREAD

**Issue by s0tt** [achalddave/large-vocab-devil#2]
Hello,
thanks for this nice work and the released code.
I couldn't find an answer in your paper regarding the values you report.
When you talk about AP in the paper do you mean mask AP or bbox AP?
I think it is not fully clear, as Mask R-CNN can produce both metrics using different IoU types.
Many thanks!

**Comment by rbgirshick** [comment]
Sorry this is unclear! All AP values in the paper are mask AP. (Mask AP is the standard on LVIS, so there is an implicit assumption of this case, but it would have been better to start this clearly.)
